//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fondital.Client.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fondital.Client.LanguageResources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilitati.
        /// </summary>
        public static string Abilitati {
            get {
                return ResourceManager.GetString("Abilitati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accedi.
        /// </summary>
        public static string Accedi {
            get {
                return ResourceManager.GetString("Accedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi.
        /// </summary>
        public static string Aggiungi {
            get {
                return ResourceManager.GetString("Aggiungi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Anagrafica.
        /// </summary>
        public static string AggiungiAnagrafica {
            get {
                return ResourceManager.GetString("AggiungiAnagrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Lavorazione.
        /// </summary>
        public static string AggiungiLavorazione {
            get {
                return ResourceManager.GetString("AggiungiLavorazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Utente.
        /// </summary>
        public static string AggiungiUtente {
            get {
                return ResourceManager.GetString("AggiungiUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anagrafica.
        /// </summary>
        public static string Anagrafica {
            get {
                return ResourceManager.GetString("Anagrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anagrafiche.
        /// </summary>
        public static string Anagrafiche {
            get {
                return ResourceManager.GetString("Anagrafiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anagrafiche Difetti.
        /// </summary>
        public static string AnagraficheDifetti {
            get {
                return ResourceManager.GetString("AnagraficheDifetti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anagrafiche Lavorazioni.
        /// </summary>
        public static string AnagraficheLavorazioni {
            get {
                return ResourceManager.GetString("AnagraficheLavorazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anagrafiche SP.
        /// </summary>
        public static string AnagraficheSP {
            get {
                return ResourceManager.GetString("AnagraficheSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anagrafiche Voci di Costo.
        /// </summary>
        public static string AnagraficheVociDiCosto {
            get {
                return ResourceManager.GetString("AnagraficheVociDiCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione.
        /// </summary>
        public static string Attenzione {
            get {
                return ResourceManager.GetString("Attenzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to è autenticato.
        /// </summary>
        public static string Autenticato {
            get {
                return ResourceManager.GetString("Autenticato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanti.
        /// </summary>
        public static string Avanti {
            get {
                return ResourceManager.GetString("Avanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto.
        /// </summary>
        public static string Benvenuto {
            get {
                return ResourceManager.GetString("Benvenuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia Password.
        /// </summary>
        public static string CambiaPassword {
            get {
                return ResourceManager.GetString("CambiaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il campo è obbligatorio.
        /// </summary>
        public static string CampoObbligatorio {
            get {
                return ResourceManager.GetString("CampoObbligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        public static string Cancella {
            get {
                return ResourceManager.GetString("Cancella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caricamento in corso.
        /// </summary>
        public static string Caricamento {
            get {
                return ResourceManager.GetString("Caricamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca SP .
        /// </summary>
        public static string CercaSP {
            get {
                return ResourceManager.GetString("CercaSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca Utenti.
        /// </summary>
        public static string CercaUtenti {
            get {
                return ResourceManager.GetString("CercaUtenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao.
        /// </summary>
        public static string Ciao {
            get {
                return ResourceManager.GetString("Ciao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Città.
        /// </summary>
        public static string Citta {
            get {
                return ResourceManager.GetString("Citta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODICE CLIENTE.
        /// </summary>
        public static string CodiceCliente {
            get {
                return ResourceManager.GetString("CodiceCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODICE FORNITORE.
        /// </summary>
        public static string CodiceFornitore {
            get {
                return ResourceManager.GetString("CodiceFornitore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string Cognome {
            get {
                return ResourceManager.GetString("Cognome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicuri di voler modificare la lavorazione #.
        /// </summary>
        public static string ConfermaModificaLavorazione {
            get {
                return ResourceManager.GetString("ConfermaModificaLavorazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è Sicuro di volere Disabilitare l&apos;utente.
        /// </summary>
        public static string ConfermaModificaUtente {
            get {
                return ResourceManager.GetString("ConfermaModificaUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è Sicuro di volere Abilitare l&apos;utente.
        /// </summary>
        public static string ConfermaModificaUtenteAb {
            get {
                return ResourceManager.GetString("ConfermaModificaUtenteAb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma Nuova Password.
        /// </summary>
        public static string ConfermaPassword {
            get {
                return ResourceManager.GetString("ConfermaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurazioni.
        /// </summary>
        public static string Configurazioni {
            get {
                return ResourceManager.GetString("Configurazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurazioni Generali.
        /// </summary>
        public static string ConfigurazioniGenerali {
            get {
                return ResourceManager.GetString("ConfigurazioniGenerali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da / a.
        /// </summary>
        public static string DataDaA {
            get {
                return ResourceManager.GetString("DataDaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dati Anagrafici.
        /// </summary>
        public static string DatiAnagrafici {
            get {
                return ResourceManager.GetString("DatiAnagrafici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dati Caldaia.
        /// </summary>
        public static string DatiCaldaia {
            get {
                return ResourceManager.GetString("DatiCaldaia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIZIONE.
        /// </summary>
        public static string DESCRIZIONE {
            get {
                return ResourceManager.GetString("DESCRIZIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difetti.
        /// </summary>
        public static string Difetti {
            get {
                return ResourceManager.GetString("Difetti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difetto.
        /// </summary>
        public static string Difetto {
            get {
                return ResourceManager.GetString("Difetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabilitati.
        /// </summary>
        public static string Disabilitati {
            get {
                return ResourceManager.GetString("Disabilitati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: verificare che la vecchia password sia corretta.
        ///La nuova password deve essere lunga almeno 8 caratteri e contenere minuscole, maiuscole, numeri e simboli..
        /// </summary>
        public static string ErroreCambioPw {
            get {
                return ResourceManager.GetString("ErroreCambioPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I campi Nuova Password e Conferma Nuova Password devono coincidere, ed essere diversi da Vecchia Password..
        /// </summary>
        public static string ErroreConfermaPassword {
            get {
                return ResourceManager.GetString("ErroreConfermaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il salvataggio dei dati, si prega di riprovare..
        /// </summary>
        public static string ErroreGenerico {
            get {
                return ResourceManager.GetString("ErroreGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;immissione dei dati: il Nome Italiano inserito esiste già..
        /// </summary>
        public static string ErroreNomeItaliano {
            get {
                return ResourceManager.GetString("ErroreNomeItaliano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;immissione dei dati: il Nome Russo inserito esiste già..
        /// </summary>
        public static string ErroreNomeRusso {
            get {
                return ResourceManager.GetString("ErroreNomeRusso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo Username o la Password sono incorretti..
        /// </summary>
        public static string ErroreUserPassword {
            get {
                return ResourceManager.GetString("ErroreUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forfettario.
        /// </summary>
        public static string Forfettario {
            get {
                return ResourceManager.GetString("Forfettario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garanzia.
        /// </summary>
        public static string Garanzia {
            get {
                return ResourceManager.GetString("Garanzia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generali.
        /// </summary>
        public static string Generali {
            get {
                return ResourceManager.GetString("Generali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione.
        /// </summary>
        public static string Gestione {
            get {
                return ResourceManager.GetString("Gestione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione Rapporti.
        /// </summary>
        public static string GestioneRapporti {
            get {
                return ResourceManager.GetString("GestioneRapporti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        public static string Impostazioni {
            get {
                return ResourceManager.GetString("Impostazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        public static string Indietro {
            get {
                return ResourceManager.GetString("Indietro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni Utente.
        /// </summary>
        public static string InformazioniUtente {
            get {
                return ResourceManager.GetString("InformazioniUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci Anagrafica.
        /// </summary>
        public static string InserisciAnagrafica {
            get {
                return ResourceManager.GetString("InserisciAnagrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci Password....
        /// </summary>
        public static string InserisciPw {
            get {
                return ResourceManager.GetString("InserisciPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci Username....
        /// </summary>
        public static string InserisciUser {
            get {
                return ResourceManager.GetString("InserisciUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervento.
        /// </summary>
        public static string Intervento {
            get {
                return ResourceManager.GetString("Intervento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavorazione.
        /// </summary>
        public static string Lavorazione {
            get {
                return ResourceManager.GetString("Lavorazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavorazioni.
        /// </summary>
        public static string Lavorazioni {
            get {
                return ResourceManager.GetString("Lavorazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listino.
        /// </summary>
        public static string Listino {
            get {
                return ResourceManager.GetString("Listino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricola.
        /// </summary>
        public static string Matricola {
            get {
                return ResourceManager.GetString("Matricola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modello.
        /// </summary>
        public static string Modello {
            get {
                return ResourceManager.GetString("Modello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        public static string Modifica {
            get {
                return ResourceManager.GetString("Modifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica Anagrafica.
        /// </summary>
        public static string ModificaAnagrafica {
            get {
                return ResourceManager.GetString("ModificaAnagrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica ServicePartner.
        /// </summary>
        public static string ModificaServicePartner {
            get {
                return ResourceManager.GetString("ModificaServicePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica SP.
        /// </summary>
        public static string ModificaSP {
            get {
                return ResourceManager.GetString("ModificaSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica Utente.
        /// </summary>
        public static string ModificaUtente {
            get {
                return ResourceManager.GetString("ModificaUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiche.
        /// </summary>
        public static string Modifiche {
            get {
                return ResourceManager.GetString("Modifiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le modifiche sono andate in errore, si prega di riprovare..
        /// </summary>
        public static string ModificheErrore {
            get {
                return ResourceManager.GetString("ModificheErrore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiche effettuate con successo..
        /// </summary>
        public static string ModificheSuccesso {
            get {
                return ResourceManager.GetString("ModificheSuccesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non hai effettuato il login.
        /// </summary>
        public static string NoLoginEffettuato {
            get {
                return ResourceManager.GetString("NoLoginEffettuato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Italiano.
        /// </summary>
        public static string NomeItaliano {
            get {
                return ResourceManager.GetString("NomeItaliano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Russo.
        /// </summary>
        public static string NomeRusso {
            get {
                return ResourceManager.GetString("NomeRusso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string NumCivico {
            get {
                return ResourceManager.GetString("NumCivico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Rapportino.
        /// </summary>
        public static string NumRapporto {
            get {
                return ResourceManager.GetString("NumRapporto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Telefonico.
        /// </summary>
        public static string NumTelefono {
            get {
                return ResourceManager.GetString("NumTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova.
        /// </summary>
        public static string Nuova {
            get {
                return ResourceManager.GetString("Nuova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova Lavorazione.
        /// </summary>
        public static string NuovaLavorazione {
            get {
                return ResourceManager.GetString("NuovaLavorazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova Password.
        /// </summary>
        public static string NuovaPassword {
            get {
                return ResourceManager.GetString("NuovaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo.
        /// </summary>
        public static string Nuovo {
            get {
                return ResourceManager.GetString("Nuovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo Difetto.
        /// </summary>
        public static string NuovoDifetto {
            get {
                return ResourceManager.GetString("NuovoDifetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ottieni Informazioni.
        /// </summary>
        public static string OttieniInformazioni {
            get {
                return ResourceManager.GetString("OttieniInformazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password dimenticata?.
        /// </summary>
        public static string PasswordDimenticata {
            get {
                return ResourceManager.GetString("PasswordDimenticata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occorre cambiare la password..
        /// </summary>
        public static string PasswordMustChange {
            get {
                return ResourceManager.GetString("PasswordMustChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo Validità.
        /// </summary>
        public static string PeriodoValidita {
            get {
                return ResourceManager.GetString("PeriodoValidita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità.
        /// </summary>
        public static string Quantita {
            get {
                return ResourceManager.GetString("Quantita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAGIONE SOCIALE.
        /// </summary>
        public static string RagioneSociale {
            get {
                return ResourceManager.GetString("RagioneSociale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapporti.
        /// </summary>
        public static string Rapporti {
            get {
                return ResourceManager.GetString("Rapporti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapporto.
        /// </summary>
        public static string Rapporto {
            get {
                return ResourceManager.GetString("Rapporto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direzione.
        /// </summary>
        public static string RuoloDirezione {
            get {
                return ResourceManager.GetString("RuoloDirezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string Salva {
            get {
                return ResourceManager.GetString("Salva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Partner.
        /// </summary>
        public static string ServicePartner {
            get {
                return ResourceManager.GetString("ServicePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        public static string Stato {
            get {
                return ResourceManager.GetString("Stato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATO DELL&apos;UTENTE.
        /// </summary>
        public static string StatoUtente {
            get {
                return ResourceManager.GetString("StatoUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPOLOGIA.
        /// </summary>
        public static string TIPOLOGIA {
            get {
                return ResourceManager.GetString("TIPOLOGIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutti.
        /// </summary>
        public static string Tutti {
            get {
                return ResourceManager.GetString("Tutti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utenti.
        /// </summary>
        public static string Utenti {
            get {
                return ResourceManager.GetString("Utenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vecchia Password.
        /// </summary>
        public static string VecchiaPassword {
            get {
                return ResourceManager.GetString("VecchiaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione.
        /// </summary>
        public static string Versione {
            get {
                return ResourceManager.GetString("Versione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via.
        /// </summary>
        public static string Via {
            get {
                return ResourceManager.GetString("Via", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voce di Costo.
        /// </summary>
        public static string VoceCosto {
            get {
                return ResourceManager.GetString("VoceCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voci di Costo.
        /// </summary>
        public static string VociCosto {
            get {
                return ResourceManager.GetString("VociCosto", resourceCulture);
            }
        }
    }
}
