//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fondital.Shared.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Display_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Display_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Fondital.Shared.Resources.Display.ru", typeof(Display_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CodiceCliente {
            get {
                return ResourceManager.GetString("CodiceCliente", resourceCulture);
            }
        }
        
        public static string CodiceFornitore {
            get {
                return ResourceManager.GetString("CodiceFornitore", resourceCulture);
            }
        }
        
        public static string Cognome {
            get {
                return ResourceManager.GetString("Cognome", resourceCulture);
            }
        }
        
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string IdFornitore {
            get {
                return ResourceManager.GetString("IdFornitore", resourceCulture);
            }
        }
        
        public static string IdRicambio {
            get {
                return ResourceManager.GetString("IdRicambio", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        public static string NomeItaliano {
            get {
                return ResourceManager.GetString("NomeItaliano", resourceCulture);
            }
        }
        
        public static string NomeRusso {
            get {
                return ResourceManager.GetString("NomeRusso", resourceCulture);
            }
        }
        
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Quantita {
            get {
                return ResourceManager.GetString("Quantita", resourceCulture);
            }
        }
        
        public static string Raggruppamento {
            get {
                return ResourceManager.GetString("Raggruppamento", resourceCulture);
            }
        }
        
        public static string RagioneSociale {
            get {
                return ResourceManager.GetString("RagioneSociale", resourceCulture);
            }
        }
        
        public static string ServicePartner {
            get {
                return ResourceManager.GetString("ServicePartner", resourceCulture);
            }
        }
        
        public static string Valore {
            get {
                return ResourceManager.GetString("Valore", resourceCulture);
            }
        }
        
        public static string VoceCosto {
            get {
                return ResourceManager.GetString("VoceCosto", resourceCulture);
            }
        }
    }
}
