//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fondital.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Display {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Display() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fondital.Shared.Resources.Display", typeof(Display).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Cliente.
        /// </summary>
        public static string CodiceCliente {
            get {
                return ResourceManager.GetString("CodiceCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Fornitore.
        /// </summary>
        public static string CodiceFornitore {
            get {
                return ResourceManager.GetString("CodiceFornitore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Italiano.
        /// </summary>
        public static string NomeItaliano {
            get {
                return ResourceManager.GetString("NomeItaliano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Russo.
        /// </summary>
        public static string NomeRusso {
            get {
                return ResourceManager.GetString("NomeRusso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raggruppamento.
        /// </summary>
        public static string Raggruppamento {
            get {
                return ResourceManager.GetString("Raggruppamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragione Sociale.
        /// </summary>
        public static string RagioneSociale {
            get {
                return ResourceManager.GetString("RagioneSociale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Partner.
        /// </summary>
        public static string ServicePartner {
            get {
                return ResourceManager.GetString("ServicePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore.
        /// </summary>
        public static string Valore {
            get {
                return ResourceManager.GetString("Valore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voce di Costo.
        /// </summary>
        public static string VoceCosto {
            get {
                return ResourceManager.GetString("VoceCosto", resourceCulture);
            }
        }
    }
}
